// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NewsFeedSentimentAnalysisML.Model
{
    public class ModelInput
    {
        [ColumnName("Date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("News"), LoadColumn(1)]
        public string News { get; set; }


        [ColumnName("sentiment"), LoadColumn(2)]
        public bool Sentiment { get; set; }


    }
}
